CREATE OR REPLACE FUNCTION UPDATE_LENDING_DELAYS()
	RETURNS VOID as $$
	BEGIN
		UPDATE lendings
		SET delays = CURRENT_DATE - end_date
		WHERE returned = FALSE
			AND end_date < CURRENT_DATE;
	END;
	$$ LANGUAGE plpgsql;
	
	